name: carla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - astunparse=1.6.3=py_0
  - atari_py=0.2.6=py37h5202443_1
  - autopep8=1.5.4=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=openblas
  - blinker=1.4=py37_0
  - box2d-py=2.3.8=py37h3340039_1
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.3.0=py_0
  - configparser=5.0.0=py_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - docker-pycreds=0.4.0=py_0
  - ephem=3.7.7.1=py37h7b6447c_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.3.1=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - fsspec=0.8.4=py_0
  - future=0.18.2=py37hc8dfbb8_1
  - gast=0.3.3=py_0
  - geos=3.8.0=he6710b0_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gitdb=4.0.5=py_0
  - gitpython=3.1.7=py_0
  - glib=2.65.0=h6f030ca_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=he1b5a44_1001
  - grpcio=1.27.2=py37hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gym=0.17.2=py37hc8dfbb8_1
  - gym-box2d=0.17.2=py37hc8dfbb8_1
  - h5py=2.10.0=py37hd6299e0_1
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=64.2=he1b5a44_1
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imageio-ffmpeg=0.4.2=py_0
  - importlib-metadata=1.7.0=py37_0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.17.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.17.2=py37_0
  - jpeg=9d=h516909a_0
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_15
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libopencv=4.4.0=py37_2
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.12.4=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.2=he1b5a44_1
  - markdown=3.2.2=py37_0
  - mkl=2020.1=217
  - moviepy=1.0.1=py_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py37hf046da1_1
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_1
  - ninja=1.10.0=py37hfd86e86_0
  - nspr=4.27=he1b5a44_1
  - nss=3.55=he751ad9_0
  - numpy=1.19.1=py37h8960a57_0
  - nvidia-ml=7.352.0=py_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openblas=0.3.10=pthreads_hf183345_4
  - opencv=4.4.0=py37_2
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1k=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.0=py37he6710b0_0
  - parso=0.7.0=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - pixman=0.38.0=h516909a_1003
  - proglog=0.1.9=py_0
  - promise=2.3=py37hc8dfbb8_1
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.12.4=py37he6710b0_0
  - psutil=5.7.2=py37h8f50634_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py37_0
  - py-opencv=4.4.0=py37h43977f1_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=py_2
  - pyglet=1.5.0=py37hc8dfbb8_1
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py37_1
  - python=3.7.8=h6f2ec95_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytorch-lightning=1.0.3=py_1
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.1=py37he6710b0_1
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scipy=1.5.0=py37habc2bb6_0
  - sentry-sdk=0.16.5=pyh9f0ad1d_0
  - setuptools=49.6.0=py37_0
  - shapely=1.7.0=py37h98ec03d_0
  - shortuuid=1.0.1=py37hc8dfbb8_2
  - six=1.15.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - sqlite=3.32.3=h62c20be_0
  - tabulate=0.8.7=py37_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py37h1a511ff_0
  - tensorflow-base=2.2.0=gpu_py37h8a81be8_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.48.2=pyh9f0ad1d_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.10=py_0
  - watchdog=0.10.3=py37hc8dfbb8_1
  - wcwidth=0.2.5=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.11=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he6710b0_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - antlr4-python3-runtime==4.8
    - dictor==0.1.7
    - gql==0.2.0
    - graphql-core==1.1
    - hydra-core==1.0.3
    - imgaug==0.4.0
    - importlib-resources==3.0.0
    - matplotlib==3.3.1
    - omegaconf==2.0.2
    - opencv-python==4.5.1.48
    - py-trees==0.8.3
    - pydot==1.4.1
    - pygame==1.9.6
    - pygccxml==2.0.1
    - pyplusplus==1.8.4
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - stable-baselines3==0.8.0
    - subprocess32==3.5.4
    - tifffile==2020.10.1
    - typing-extensions==3.7.4.3
    - wandb==0.10.12